# Generated by Django 4.2 on 2023-04-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('WEB', ' Web'), ('DESKTOP', 'Desktop'), ('ANALYSIS', 'Analysis')], default='WEB', max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('project_date', models.DateField()),
                ('project_url', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
