# Generated by Django 4.2 on 2023-04-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_pictures_image_alter_projects_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('WEB', ' Web'), ('APP', 'App'), ('ANALYSIS', 'Analysis')], default='WEB', max_length=50),
        ),
    ]
