# Generated by Django 4.2 on 2023-04-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projects_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='slug',
        ),
    ]
